
import * as admin from 'firebase-admin';
import * as path from 'path';

// ═══════════════════════════════════════════════════
// Initialize Admin SDK for LIVE Firestore
// Uses the service account key — NOT the emulator
// ═══════════════════════════════════════════════════
if (!admin.apps.length) {
  const serviceAccount = require(
    path.resolve(__dirname, '..', 'nattufeed-d59c9-firebase-adminsdk-fbsvc-f3dff68116.json')
  );
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
  });
}

const db = admin.firestore();

const TEST_USERS = [
  // ── Kannur Users ──
  { uid: 'knr_user_1', name: 'Akhil M', photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Akhil' },
  { uid: 'knr_user_2', name: 'Sreelakshmi R', photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sreelakshmi' },
  { uid: 'knr_user_3', name: 'Vineeth Kumar', photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vineeth' },
  { uid: 'knr_user_4', name: 'Fathima N', photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fathima' },
  { uid: 'knr_user_5', name: 'Suresh Babu', photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Suresh' },
  { uid: 'knr_user_6', name: 'Priya Menon', photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya' },
  { uid: 'knr_user_7', name: 'Nishanth T', photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nishanth' },
  { uid: 'knr_user_8', name: 'Divya Krishnan', photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Divya' },
];

// ── Kannur user → location mapping ──
const KANNUR_USER_PROFILES: Record<string, { district: string; localBody: string; ward?: string }> = {
  knr_user_1: { district: 'Kannur', localBody: 'Kannur', ward: 'Fort Area' },
  knr_user_2: { district: 'Kannur', localBody: 'Thalassery Municipality', ward: 'Thalassery Town' },
  knr_user_3: { district: 'Kannur', localBody: 'Payyannur Municipality', ward: 'Payyannur Central' },
  knr_user_4: { district: 'Kannur', localBody: 'Thaliparambu Municipality', ward: 'Taliparamba Town' },
  knr_user_5: { district: 'Kannur', localBody: 'Iritty Municipality', ward: 'Iritty Town' },
  knr_user_6: { district: 'Kannur', localBody: 'Mattannur Municipality', ward: 'Mattannur Town' },
  knr_user_7: { district: 'Kannur', localBody: 'Panoor Municipality', ward: 'Panoor Junction' },
  knr_user_8: { district: 'Kannur', localBody: 'Koothuparamba Municipality', ward: 'Koothuparamba Town' },
};

// ── Kannur area coordinates (real approximate centers) ──

const seedLive = async () => {
  console.log('🚀 Seeding Kannur data to LIVE Firestore...');
  console.log('⚠️  This writes to your PRODUCTION database!\n');

  try {
    // ═══════════════════════════════════════════════════
    // 1. Seed Kannur Users
    // ═══════════════════════════════════════════════════
    for (const u of TEST_USERS) {
      const loc = KANNUR_USER_PROFILES[u.uid];
      await db.collection('users').doc(u.uid).set({
        displayName: u.name,
        photoURL: u.photo,
        karmaTotal: Math.floor(Math.random() * 400) + 20,
        karmaWeekly: Math.floor(Math.random() * 40) + 5,
        district: loc.district,
        localBody: loc.localBody,
        ward: loc.ward,
        createdAt: admin.firestore.FieldValue.serverTimestamp()
      });
      console.log(`   ✅ User: ${u.name} → ${loc.localBody}`);
    }

    // ═══════════════════════════════════════════════════
    // 2. Delete old seeded posts by knr_user authors
    // ═══════════════════════════════════════════════════
    const knrUserIds = TEST_USERS.map(u => u.uid);
    for (const uid of knrUserIds) {
      const oldPosts = await db.collection('posts').where('authorId', '==', uid).get();
      for (const doc of oldPosts.docs) {
        await doc.ref.delete();
        console.log(`   🗑️  Deleted: ${doc.id}`);
      }
    }

    // ═══════════════════════════════════════════════════
    // 3. Seed Kannur Posts (fresh, no authorPhoto)
    // ═══════════════════════════════════════════════════
    const EVERGREEN_POSTS = [
      {
        authorId: 'knr_user_1',
        authorName: 'Akhil M',
        headline: 'Thavakkara vs Old Stand Confusion 🚌',
        details: 'Long distance (Kozhikode/Kochi) buses New Bus Stand-il aanu varunne. Pakshe local city buses (Talap, Pallikunnu) ellam Old Bus Stand-il ninnu aanu start cheyyunne. Maari pogaile tto!',
        landmark: 'Kannur Old Bus Stand',
        category: 'Traffic',
        type: 'general',
        lat: 11.8760,
        lng: 75.3660,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Stadium Corner',
        verifiedCount: 15,
        reactions: { verified: 15, hot: 1, helpful: 20, interesting: 2 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_2',
        authorName: 'Sreelakshmi R',
        headline: 'Thalassery Fish Market Fresh Arrivals 🐟',
        details: 'Nalla fresh meen venamenkil raavile 07:00-nu munbe Thalassery Market-il ethuna nallath. Harbour-il ninnu appol varunna fresh items kuranja vilayil kittaum.',
        landmark: 'Thalassery Fish Market',
        category: 'Market',
        type: 'general',
        lat: 11.7480,
        lng: 75.4890,
        district: 'Kannur',
        localBody: 'Thalassery Municipality',
        ward: 'Market Ward',
        verifiedCount: 18,
        reactions: { verified: 18, hot: 2, helpful: 12, interesting: 1 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_1',
        authorName: 'Akhil M',
        headline: 'Payyambalam Beach Safety Alert 🌊',
        details: 'Beach-il ippo thirool (waves) kurach kooduthal aanu. Lifeguard parayunne pole mathram kadalil iranguka. Evening vibes-inu poyko, pakshe safety sradhikkanam.',
        landmark: 'Payyambalam Beach',
        category: 'Alerts',
        type: 'general',
        lat: 11.8725,
        lng: 75.3530,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Payyambalam',
        verifiedCount: 25,
        reactions: { verified: 25, hot: 0, helpful: 30, interesting: 5 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_3',
        authorName: 'Vineeth Kumar',
        headline: 'Payyanur KSEB Complaint Office ⚡',
        details: 'Current poyaal toll-free number 1912-il vilichal mathi. Payyanur town area-yil service fast aanu. Innu raathri maintenance work illa tto.',
        landmark: 'Payyanur KSEB Office',
        category: 'Utility',
        type: 'general',
        lat: 12.1060,
        lng: 75.2070,
        district: 'Kannur',
        localBody: 'Payyanur Municipality',
        ward: 'Central Ward',
        verifiedCount: 9,
        reactions: { verified: 9, hot: 0, helpful: 14, interesting: 0 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_5',
        authorName: 'Suresh Babu',
        headline: 'Iritty Night Pharmacy Access 💊',
        details: 'Emergency aayi raathri marunnu venamenkil Iritty Town-ile Main Junction-ile medical shops midnight vare open aakaarundu. General medicines eppoalum kittaum.',
        landmark: 'Iritty Town Junction',
        category: 'Health',
        type: 'general',
        lat: 11.8460,
        lng: 75.6390,
        district: 'Kannur',
        localBody: 'Iritty Municipality',
        ward: 'Iritty Town',
        verifiedCount: 12,
        reactions: { verified: 12, hot: 1, helpful: 18, interesting: 0 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_6',
        authorName: 'Priya Menon',
        headline: 'Mattannur Auto Stand Rates 🚕',
        details: 'Mattannur Stand-il meter charge mathrame nalkendullu. Night charges 10 PM kazhinjal maaraum. Chart stand-il display cheythitundu, sradhikkuka.',
        landmark: 'Mattannur Auto Stand',
        category: 'Traffic',
        type: 'general',
        lat: 11.9310,
        lng: 75.5740,
        district: 'Kannur',
        localBody: 'Mattannur Municipality',
        ward: 'Town Ward',
        verifiedCount: 7,
        reactions: { verified: 7, hot: 0, helpful: 10, interesting: 1 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_4',
        authorName: 'Fathima N',
        headline: 'Taliparamba Junction Peak Hour Block 🚦',
        details: 'Raavile 9AM-num vaikunneram 5PM-num Junction-il nalla block undaakum. Bypass vazhi poyaal time labhikkaam. Two-wheelers sradhikkanam.',
        landmark: 'Taliparamba Junction',
        category: 'Alerts',
        type: 'general',
        lat: 12.0370,
        lng: 75.3600,
        district: 'Kannur',
        localBody: 'Thaliparambu Municipality',
        ward: 'Taliparamba Town',
        verifiedCount: 22,
        reactions: { verified: 22, hot: 5, helpful: 15, interesting: 2 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_7',
        authorName: 'Nishanth T',
        headline: 'Panoor Sunday Market Nadan Veggies 🌶️',
        details: 'Sunday market-il nalla nadan mulaku, payar, kariveppila okke kittaum. Local farmers direct kondu varunath aanu. Kuranja vila-um kittaum.',
        landmark: 'Panoor Market Ground',
        category: 'Market',
        type: 'general',
        lat: 11.8060,
        lng: 75.5410,
        district: 'Kannur',
        localBody: 'Panoor Municipality',
        ward: 'Market Ward',
        verifiedCount: 6,
        reactions: { verified: 6, hot: 1, helpful: 8, interesting: 3 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_8',
        authorName: 'Divya Krishnan',
        headline: 'Koothuparamba PHC Token System 🏥',
        details: 'General OP check-up raavile 08:30-nu start cheiyyum. Injection-u kooduthal wait cheiyyendi varum, so raavile thanne poyi token edukkaunne nallath.',
        landmark: 'Koothuparamba PHC',
        category: 'Health',
        type: 'general',
        lat: 11.8650,
        lng: 75.5500,
        district: 'Kannur',
        localBody: 'Koothuparamba Municipality',
        ward: 'Town Ward',
        verifiedCount: 11,
        reactions: { verified: 11, hot: 0, helpful: 14, interesting: 0 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_1',
        authorName: 'Akhil M',
        headline: 'Railway Station 2nd Entry Hack 🚂',
        details: 'Main gate-il thirakku aairikkum. Pazhaya Bus Stand bhagathulla 2nd entry vazhi poyaal thirakku illathe platform-il keraam. Parking-um avide undu.',
        landmark: 'Kannur Railway Station',
        category: 'Traffic',
        type: 'general',
        lat: 11.8718,
        lng: 75.3676,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Station Road',
        verifiedCount: 19,
        reactions: { verified: 19, hot: 2, helpful: 25, interesting: 4 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_2',
        authorName: 'Sreelakshmi R',
        headline: 'Thalassery Pier Evening Vibes 🌅',
        details: 'Evening-il onnu relax cheyyaan Thalassery Pier (Kadal Palam) nallath aanu. Friends-inte koode chai okke kudichu kadal kaanaam. Photos sradhikkanam.',
        landmark: 'Thalassery Pier',
        category: 'TownTalk',
        type: 'general',
        lat: 11.7450,
        lng: 75.4850,
        district: 'Kannur',
        localBody: 'Thalassery Municipality',
        ward: 'Pier Ward',
        verifiedCount: 16,
        reactions: { verified: 16, hot: 3, helpful: 5, interesting: 20 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_1',
        authorName: 'Akhil M',
        headline: 'St. Angelo Fort Timing Reminder 🏰',
        details: 'Fort-ilekk entry 08:30 AM thottu 06:00 PM vare aanu. Entry fee ₹25 (Indians). Vaikunneram 4 mani kazhinju poyal nalla vibe aanu. Family aayi poyko!',
        landmark: 'St. Angelo Fort',
        category: 'TownTalk',
        type: 'general',
        lat: 11.8594,
        lng: 75.3784,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Burnacherry',
        verifiedCount: 12,
        reactions: { verified: 12, hot: 1, helpful: 8, interesting: 15 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_4',
        authorName: 'Fathima N',
        headline: 'Taliparamba Civil Station Ration Card Help 🌾',
        details: 'Ration card-ile details maattaanum puthiyath cherkaanum Civil Station-ile office-il poyaal mathi. Wednesday-il thirakku kooduthal aakaarundu.',
        landmark: 'Taliparamba Civil Station',
        category: 'Utility',
        type: 'general',
        lat: 12.0410,
        lng: 75.3620,
        district: 'Kannur',
        localBody: 'Thaliparambu Municipality',
        ward: 'Civil Station Ward',
        verifiedCount: 8,
        reactions: { verified: 8, hot: 0, helpful: 10, interesting: 1 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_5',
        authorName: 'Suresh Babu',
        headline: 'Iritty Plumber/Electrician Service Help 🚰',
        details: 'Emergency aayi plumbing works-inu aale venamenkil Stand-inte aduthulla hardware shops-il chodichaal mathi. Local technicians contact kittaum.',
        landmark: 'Iritty Bus Stand',
        category: 'Services',
        type: 'general',
        lat: 11.8475,
        lng: 75.6410,
        district: 'Kannur',
        localBody: 'Iritty Municipality',
        ward: 'Stand Ward',
        verifiedCount: 5,
        reactions: { verified: 5, hot: 0, helpful: 7, interesting: 0 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_3',
        authorName: 'Vineeth Kumar',
        headline: 'Payyanur Haritha Karma Sena Plastic Collection ♻️',
        details: 'Municipality-il plastic collection monthly nadakkaaruundu. Veetilekk aalu varumbol clean aayi plastic nalkuka. Town clean aayi vaikkaam!',
        landmark: 'Payyanur Town',
        category: 'Utility',
        type: 'general',
        lat: 12.1060,
        lng: 75.2070,
        district: 'Kannur',
        localBody: 'Payyannur Municipality',
        ward: 'Payyannur Central',
        verifiedCount: 10,
        reactions: { verified: 10, hot: 0, helpful: 12, interesting: 1 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_6',
        authorName: 'Priya Menon',
        headline: 'Mattannur KSEB Section Contact Option ⚡',
        details: 'Current poyaal 1912 online complaint cheyyaam. Mattannur town area-yil response fast aanenkilum raathri delay varaum, sradhikkuka.',
        landmark: 'Mattannur Town',
        category: 'Utility',
        type: 'general',
        lat: 11.9300,
        lng: 75.5730,
        district: 'Kannur',
        localBody: 'Mattannur Municipality',
        ward: 'Mattannur Town',
        verifiedCount: 6,
        reactions: { verified: 6, hot: 0, helpful: 9, interesting: 0 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_7',
        authorName: 'Nishanth T',
        headline: 'Panoor Evening Foodie Spots 🍗',
        details: 'Panoor Junction-il vaikunneram nalla Alfaham and Mandi kittaunne shops undu. Friends-inte koode hangout cheyyaan nalla place aanu.',
        landmark: 'Panoor Junction',
        category: 'TownTalk',
        type: 'general',
        lat: 11.8050,
        lng: 75.5400,
        district: 'Kannur',
        localBody: 'Panoor Municipality',
        ward: 'Panoor Junction',
        verifiedCount: 14,
        reactions: { verified: 14, hot: 2, helpful: 6, interesting: 12 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_8',
        authorName: 'Divya Krishnan',
        headline: 'Koothuparamba Market Ration Shop Status 🌾',
        details: 'Market-ile ration shop renovation kazhinju reopen cheythidundu. Card-il kittaunna items ellam eppoal avide kittaum. Timing sradhikkuka.',
        landmark: 'Koothuparamba Market',
        category: 'Utility',
        type: 'general',
        lat: 11.8650,
        lng: 75.5510,
        district: 'Kannur',
        localBody: 'Koothuparamba Municipality',
        ward: 'Market Ward',
        verifiedCount: 8,
        reactions: { verified: 8, hot: 0, helpful: 10, interesting: 1 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_1',
        authorName: 'Akhil M',
        headline: 'Ayikkara Harbour Morning Fresh Catch 🐟',
        details: 'Market-inekkaal kuranja vilayil fresh meen venamenkil raavile Harbour-il pogaunne nallath. Wholesale rates-il kittaum. Early morning vibe nallath aanu.',
        landmark: 'Ayikkara Fishing Harbour',
        category: 'Market',
        type: 'general',
        lat: 11.8545,
        lng: 75.3722,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Ayikkara',
        verifiedCount: 11,
        reactions: { verified: 11, hot: 2, helpful: 9, interesting: 4 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_2',
        authorName: 'Sreelakshmi R',
        headline: 'Thalassery Town Hall Study Space 📚',
        details: 'Thalassery-il quiet space and study room venamenkil Town Hall bhagathu facilities undu. Reading room access kittaum. Morning hours empty aakaarundu.',
        landmark: 'Thalassery Town Hall',
        category: 'Services',
        type: 'general',
        lat: 11.7505,
        lng: 75.4912,
        district: 'Kannur',
        localBody: 'Thalassery Municipality',
        ward: 'Town Hall Ward',
        verifiedCount: 5,
        reactions: { verified: 5, hot: 0, helpful: 7, interesting: 2 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      }
    ];

    for (let i = 0; i < EVERGREEN_POSTS.length; i++) {
      const p = EVERGREEN_POSTS[i];
      const ref = await db.collection('posts').add({
        ...p,
        createdAt: admin.firestore.Timestamp.fromMillis(Date.now() - (EVERGREEN_POSTS.length - i) * 3600000),
      });
      console.log(`   📝 [${ref.id}] ${p.headline.substring(0, 45)}...`);
    }

    // ═══════════════════════════════════════════════════
    // 4. Seed Neighborhood Posts (Azhikode, Chalad, Payyambalam area)
    // ═══════════════════════════════════════════════════
    const NEIGHBORHOOD_POSTS = [
      // --- VANKULATHVAYAL ---
      {
        authorId: 'knr_user_1',
        authorName: 'Akhil M',
        headline: 'Vankulathvayal-ile Fresh Meen Market 🐟',
        details: 'Azhikode bhagathulla nalla fish market aanu Vankulathvayal. Raavile 9 mani thottu rathri 8 vare fresh meen kittaum. Nadan ayala-yum mathi-yum eppoalum stock undaavum.',
        landmark: 'Vankulathuvayal Fish Market',
        category: 'Market',
        type: 'general',
        lat: 11.9052,
        lng: 75.3405,
        district: 'Kannur',
        localBody: 'Azhikode Panchayat',
        ward: 'Vankulathvayal',
        verifiedCount: 12,
        reactions: { verified: 12, hot: 1, helpful: 8, interesting: 2 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      // --- AZHIKODE ---
      {
        authorId: 'knr_user_4',
        authorName: 'Fathima N',
        headline: 'Meenkunnu Beach View Point Caution 🌊',
        details: 'Azhikode Meenkunnu cliff-il ninnu sunset kaanaan nalla vibe aanu. Pakshe cliff-inte edge-il nilkkumbo sradhikkuka. Mazha samayathu slippery aakaan chance undu.',
        landmark: 'Meenkunnu View Point',
        category: 'Alerts',
        type: 'general',
        lat: 11.9165,
        lng: 75.3284,
        district: 'Kannur',
        localBody: 'Azhikode Panchayat',
        ward: 'Meenkunnu',
        verifiedCount: 18,
        reactions: { verified: 18, hot: 4, helpful: 10, interesting: 5 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_7',
        authorName: 'Nishanth T',
        headline: 'Azhikkal Estuary & Port Visit ⛴️',
        details: 'Valapattanam puzhayum kadalum sangamikkunna Azhikkal nalla oru spot aanu. Evening walk-inu pogaam. Avide oru fishing harbour-um cheriya port-um undu.',
        landmark: 'Azhikkal Ferry Terminal',
        category: 'TownTalk',
        type: 'general',
        lat: 11.9428,
        lng: 75.3212,
        district: 'Kannur',
        localBody: 'Azhikode Panchayat',
        ward: 'Azhikode North',
        verifiedCount: 9,
        reactions: { verified: 9, hot: 0, helpful: 4, interesting: 15 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      // --- POOTHAPPARA ---
      {
        authorId: 'knr_user_8',
        authorName: 'Divya Krishnan',
        headline: 'Akshaya Poothappara E-Services 💻',
        details: 'Azhikode South area-yil documentation and online forms-inu Poothappara Akshaya center easy aanu. Morning hours-il poyaal thirakku kuravaairikkum.',
        landmark: 'Akshaya Poothappara',
        category: 'Services',
        type: 'general',
        lat: 11.9025,
        lng: 75.3458,
        district: 'Kannur',
        localBody: 'Azhikode Panchayat',
        ward: 'Azhikode South',
        verifiedCount: 7,
        reactions: { verified: 7, hot: 0, helpful: 12, interesting: 0 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      // --- MOONUNIRATH ---
      {
        authorId: 'knr_user_3',
        authorName: 'Vineeth Kumar',
        headline: 'Moonnunirath Junction Road Guide 🛣️',
        details: 'Moonnunirath oru main junction aanu. Ivide ninnu oru vazhi Meenkunnu beach-ilekkum mattonnu Azhikkal port-ilekkum pogaam. Local shops ellam ivide undu.',
        landmark: 'Moonnunirath Junction',
        category: 'Traffic',
        type: 'general',
        lat: 11.9212,
        lng: 75.3365,
        district: 'Kannur',
        localBody: 'Azhikode Panchayat',
        ward: 'Azhikode North',
        verifiedCount: 5,
        reactions: { verified: 5, hot: 0, helpful: 9, interesting: 1 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      // --- ALAVIL ---
      {
        authorId: 'knr_user_2',
        authorName: 'Sreelakshmi R',
        headline: 'Shirdi Sai Baba Mandir Alavil 🛕',
        details: 'Alavil bhagathulla nalla oru temple aanu Sai Baba Mandir. Raavile 5:00 muthal rathri 9:00 vare open aanu. Evening bhajan samayathu nalla shanthamaaya vibe aanu.',
        landmark: 'Shirdi Sree Sai Baba Mandir',
        category: 'TownTalk',
        type: 'general',
        lat: 11.8845,
        lng: 75.3612,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Alavil',
        verifiedCount: 14,
        reactions: { verified: 14, hot: 1, helpful: 5, interesting: 10 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_6',
        authorName: 'Priya Menon',
        headline: 'Alavil Post Office Location 📮',
        details: 'Alavil Junction-inu aduthaayi thanne aanu Post Office. Speed post and cheriya savings schemes-inu useful aanu. Working hours: 10 AM to 4 PM.',
        landmark: 'Alavil Post Office',
        category: 'Utility',
        type: 'general',
        lat: 11.8838,
        lng: 75.3625,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Alavil',
        verifiedCount: 4,
        reactions: { verified: 4, hot: 0, helpful: 7, interesting: 0 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      // --- CHALLAD ---
      {
        authorId: 'knr_user_1',
        authorName: 'Akhil M',
        headline: 'Chalad Beach Evening Relaxing Spot 🌊',
        details: 'Payyambalam beach-inte oru extension aanu Chalad beach. Main beach-inekaalum thirakku kuravaairikkum ivide. Walk-inu pogaan nalla place aanu.',
        landmark: 'Chalad Beach',
        category: 'TownTalk',
        type: 'general',
        lat: 11.8785,
        lng: 75.3522,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Chalad',
        verifiedCount: 20,
        reactions: { verified: 20, hot: 3, helpful: 8, interesting: 15 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      // --- PADANAPALAM ---
      {
        authorId: 'knr_user_5',
        authorName: 'Suresh Babu',
        headline: 'Padanapalam Bus Stop Info 🚌',
        details: 'Alavil-Azhikode route-il pokunna bus-ukal Padanapalam stop-il nirkkaaruundu. City-ilekk pogaunnavarkku ivide ninnu bus keraam.',
        landmark: 'Padanna Paalam Bus Stop',
        category: 'Traffic',
        type: 'general',
        lat: 11.8892,
        lng: 75.3585,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Azhikode South',
        verifiedCount: 6,
        reactions: { verified: 6, hot: 0, helpful: 5, interesting: 0 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      // --- PAYYAMBALAM ---
      {
        authorId: 'knr_user_1',
        authorName: 'Akhil M',
        headline: 'Payyambalam Beach Safety - Red Flag Alert 🚩',
        details: 'Kadalil thirool (waves) kooduthalaayaal lifeguards Red Flag vaikkaaruundu. Aa samayathu kadalil iranguthu. Nammude safety aanu main.',
        landmark: 'Payyambalam Beach',
        category: 'Alerts',
        type: 'general',
        lat: 11.8725,
        lng: 75.3530,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Payyambalam',
        verifiedCount: 35,
        reactions: { verified: 35, hot: 2, helpful: 45, interesting: 3 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_2',
        authorName: 'Sreelakshmi R',
        headline: 'Mother and Child Sculpture at Payyambalam 🗿',
        details: 'Payyambalam park-il Kanayi Kunhiraman-te "Mother and Child" sculpture undu. Photography-kku nalla spot aanu. Park entry evening vibe-inu kooduthal nallath.',
        landmark: 'Payyambalam Beach Garden',
        category: 'TownTalk',
        type: 'general',
        lat: 11.8705,
        lng: 75.3552,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Payyambalam',
        verifiedCount: 15,
        reactions: { verified: 15, hot: 0, helpful: 6, interesting: 22 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      // --- SN PARK ---
      {
        authorId: 'knr_user_1',
        authorName: 'Akhil M',
        headline: 'SN Park Timings for Morning Walk 🚶',
        details: 'Payyambalam area-yil ulla SN Park raavile 7:00 AM muthal 8:00 AM vare walk-inu open aanu. Vaikunneram 3:00 PM to 8:00 PM children-u play area use cheyyaam.',
        landmark: 'S N Park',
        category: 'TownTalk',
        type: 'general',
        lat: 11.8685,
        lng: 75.3582,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Payyambalam',
        verifiedCount: 11,
        reactions: { verified: 11, hot: 0, helpful: 14, interesting: 1 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      // --- MIXED ADDITIONAL ---
      {
        authorId: 'knr_user_4',
        authorName: 'Fathima N',
        headline: 'Fresh Veggies near Poothappara 🥦',
        details: 'Poothappara junction-inu aduthaulla cheriya shops-il nadan pachakkari raavile kittaum. Nalla fresh items aairikkum.',
        landmark: 'Poothappara Junction',
        category: 'Market',
        type: 'general',
        lat: 11.9018,
        lng: 75.3462,
        district: 'Kannur',
        localBody: 'Azhikode Panchayat',
        ward: 'Azhikode South',
        verifiedCount: 5,
        reactions: { verified: 5, hot: 0, helpful: 6, interesting: 1 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_7',
        authorName: 'Nishanth T',
        headline: 'Azhikkal Ferry Mattool Service Update ⛴️',
        details: 'Azhikkal-Mattool ferry service raavile 6:30 thottu rathri 9 vare undu. Mazha kooduthalaayaal service break aakaan chance undu, sradhikkuka.',
        landmark: 'Azhikkal Ferry',
        category: 'Traffic',
        type: 'general',
        lat: 11.9435,
        lng: 75.3225,
        district: 'Kannur',
        localBody: 'Azhikode Panchayat',
        ward: 'Azhikode North',
        verifiedCount: 8,
        reactions: { verified: 8, hot: 0, helpful: 10, interesting: 1 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_8',
        authorName: 'Divya Krishnan',
        headline: 'Chalad Sree Dharma Shastha Temple 🛕',
        details: 'Chalad-ile pradhaana temple aanu Shastha temple. Deeparadhana samayathu nalla crowd undaakaarundu. Cultural events-inu pradhaana center aanu.',
        landmark: 'Chalad Sree Dharma Shastha temple',
        category: 'TownTalk',
        type: 'general',
        lat: 11.8795,
        lng: 75.3535,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Chalad',
        verifiedCount: 13,
        reactions: { verified: 13, hot: 1, helpful: 4, interesting: 9 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_3',
        authorName: 'Vineeth Kumar',
        headline: 'Moonnunirath Junction Auto Stand 🚕',
        details: 'Azhikode North-ile pradhaana auto stand aanu Moonnunirath-ileth. Ferry bhagathekkum town-ilekkum pokaan ivide ninnu auto kittaum.',
        landmark: 'Moonnunirath Auto Stand',
        category: 'Traffic',
        type: 'general',
        lat: 11.9215,
        lng: 75.3368,
        district: 'Kannur',
        localBody: 'Azhikode Panchayat',
        ward: 'Azhikode North',
        verifiedCount: 7,
        reactions: { verified: 7, hot: 0, helpful: 8, interesting: 0 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_1',
        authorName: 'Akhil M',
        headline: 'Payyambalam Beach Corniche Walk 🌅',
        details: 'Nalla clean aayi maintain cheiyyunna walkway aanu Payyambalam-ileth. Evening walk and fresh air-inu best place aanu Kannur-il.',
        landmark: 'Payyambalam Beach Corniche',
        category: 'TownTalk',
        type: 'general',
        lat: 11.8712,
        lng: 75.3540,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Payyambalam',
        verifiedCount: 19,
        reactions: { verified: 19, hot: 2, helpful: 12, interesting: 10 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      },
      {
        authorId: 'knr_user_4',
        authorName: 'Fathima N',
        headline: 'Chalad Beach Market Prices 🐠',
        details: 'Chalad beach bhagathulla cheriya kooda-meen vendors-inte aduthu fresh meen kittaum. Harbour-il pokaan kazhiyaathavarkku nallath aanu.',
        landmark: 'Chalad Beach Area',
        category: 'Market',
        type: 'general',
        lat: 11.8788,
        lng: 75.3525,
        district: 'Kannur',
        localBody: 'Kannur Municipal Corporation',
        ward: 'Chalad',
        verifiedCount: 6,
        reactions: { verified: 6, hot: 0, helpful: 5, interesting: 1 },
        flagCount: 0,
        isHidden: false,
        isBusinessPost: false,
      }
    ];

    for (let i = 0; i < NEIGHBORHOOD_POSTS.length; i++) {
      const p = NEIGHBORHOOD_POSTS[i];
      const ref = await db.collection('posts').add({
        ...p,
        createdAt: admin.firestore.Timestamp.fromMillis(Date.now() - (NEIGHBORHOOD_POSTS.length - i) * 1800000),
      });
      console.log(`   🏘️ [${ref.id}] ${p.headline.substring(0, 45)}...`);
    }

   
    console.log('\n✅ Kannur Seed Complete on LIVE Firestore!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seeding failed:', err);
    process.exit(1);
  }
};

seedLive();
